when st-create-help-workspaces is run, create the Jumpstart workspace in the default-account, not Socialtext

diff --git a/nlw/bin/st-create-help-workspace b/nlw/bin/st-create-help-workspace
--- a/nlw/bin/st-create-help-workspace
+++ b/nlw/bin/st-create-help-workspace
@@ -1,17 +1,45 @@
 #!/bin/sh
 set -e
 
+ACCOUNT="Socialtext"
+
+PROGNAME=$(basename $0)
+SHORTOPTS="da:h"
+LONGOPTS="dry-run,account:,help"
+
+OPTS=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$PROGNAME" -- "$@")
+if [ $? -ne 0 ]; then
+    echo "'$progname --help' for more information" 1>&2
+    exit 1
+fi
+
+eval set -- "$OPTS"
+
 # Parse command line options.
-case "$1" in
-    --dry-run)
-        DRYRUN=1
-        shift
-        ;;
-    --help)
-        echo "Usage: $0 [--dry-run] [tarball to import]"
-        exit 1
-        ;;
-esac
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -d | --dry-run)
+            DRYRUN=1
+            shift
+            ;;
+        -a | --account)
+            ACCOUNT=$2
+            shift 2
+            ;;
+        -h | --help)
+            echo "Usage: $0 [--dry-run] [--account account_name] [tarball to import]"
+            exit 1
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            echo "Error processing option: $1" 1>&2
+            exit 1;
+            ;;
+    esac
+done
 
 # Add DIRNAME and DIRNAME/../bin to PATH, so this works in dev-envs.
 DIRNAME=$(dirname $0)
@@ -25,7 +53,7 @@ TARBALL=${1:-"$DIRNAME/../share/l10n/help/help-en.tar.gz"}
 TARBALL=$(abs_path $TARBALL)
 WS_NAME=$(echo `basename $TARBALL` | cut -f 1 -d .)
 
-echo "Preparing to update workspace $WS_NAME."
+echo "Preparing to update workspace $WS_NAME in account $ACCOUNT."
 
 # Make sure the tarball exists
 if [ ! -r $TARBALL ]; then 
@@ -37,7 +65,7 @@ fi
 STADMIN=$(abs_path `which st-admin`)
 DELETE="$STADMIN delete-workspace --workspace $WS_NAME --no-export --ceqlotron"
 IMPORT="$STADMIN import-workspace --tarball $TARBALL --noindex"
-ASSIGN="$STADMIN set-workspace-config --workspace $WS_NAME account_name Socialtext"
+ASSIGN="$STADMIN set-workspace-config --workspace $WS_NAME account_name $ACCOUNT"
 REINDEX="$STADMIN index-workspace --workspace $WS_NAME --sync --ceqlotron"
 
 # Check that we found the st-admin command.
@@ -48,6 +76,7 @@ fi
 
 # Turn commands into echos if --dry-run was given.
 if [ -n "$DRYRUN" ]; then
+    echo "Dry running..."
     DELETE="echo $DELETE"
     IMPORT="echo $IMPORT"
     ASSIGN="echo $ASSIGN"
diff --git a/nlw/bin/st-create-help-workspaces b/nlw/bin/st-create-help-workspaces
--- a/nlw/bin/st-create-help-workspaces
+++ b/nlw/bin/st-create-help-workspaces
@@ -12,10 +12,16 @@ fi
 echo "Searching $SHAREDIR for help documentation."
 for help in $SHAREDIR/help-*.tar.gz; do
     if [ -e "$help" ]; then
-       help_file=`basename $help`
-       echo "========== $help_file =========="
-       $DIR/st-create-help-workspace $help || echo "FAILED TO LOAD $help_file"
-       echo
+        help_file=`basename $help`
+        echo "========== $help_file =========="
+        ACCTOPT=""
+        JUMPSTART=`(echo "$help_file" | grep "^help-jumpstart") >/dev/null; echo $?`
+        if [ "$JUMPSTART" == "0" ]; then
+            ACCT=`$DIR/st-default-account`
+            ACCTOPT="--account $ACCT";
+        fi
+        $DIR/st-create-help-workspace $ACCTOPT $help || echo "FAILED TO LOAD $help_file"
+        echo
     fi
 done
 
